# Generated by Django 3.1.2 on 2021-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('text', models.TextField(verbose_name='Полный текст задачи в формате LaTeX')),
                ('score', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
